### ISSUE TITLE
$global variables incorrect

### ISSUE THREAD

**Issue by seb86** [BoilWP/Boilerplate-Generator#6]
When renaming the global variable of the plugin, it needs to be underscore not dash. This is causing the generated plugin to break.

Example from recent test.

This: `$GLOBALS['beautiful-car-collection']` should be this `$GLOBALS['beautiful_car_collection']`

This: `$beautiful-car-collection` should be this `$beautiful_car_collection`

**Comment by soulseekah** [comment]
Should be fixed in a557766a77608799edb0c83d2571565aa4a9a912

**Comment by seb86** [comment]
Fixed!
